### ISSUE TITLE
Austrian Holiday

### ISSUE THREAD

**Issue by airfrank** [galgtonold/jollyday-android#2]
Hi!
Thanks for your work, it's great!!

There was a bug in svendiedrichsen/jollyday.
Austrian holiday 11.11 had description undefined, because of wrong descriptionPropertiesKey in the xml file.
It was "MARTINS_TAG" and should be "MARTINS_DAY".

Maybe you can fix it too, or update to the latest version.

Best regards
Frank

**Comment by galgtonold** [comment]
Hey Frank,

glad you like this project and thank you very much for the information on the issue!

I'll take care of the situation and let you know when I resolved the bug :)

Best,
Philipp

**Comment by galgtonold** [comment]
In the meantime I was able to update the holiday definitions and descriptions, therefore this and a couple of other related issues should now be resolved with the new version! :)
