### ISSUE TITLE
Gradle fail with latest version

### ISSUE THREAD

**Issue by airfrank** [galgtonold/jollyday-android#3]
Hi Philipp, 
thanks for fixing the bug that fast!
But now, I can't use it anymore. Gradle sync failed.
0.1.8 -> Error:Failed to resolve: annotationProcessor

best regards 
Frank

**Comment by galgtonold** [comment]
Hey Frank,
my bad, I did a small mistake with the deployment of the library to jcenter. This problem should now hopefully be resolved with version 0.1.9!

Best regards,
Philipp
